// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYiFz0eRv_HW486EWPsSvvzFPMtwtHaS8',
    appId: '1:340037914709:web:6b48c0074a5541a33ec4dc',
    messagingSenderId: '340037914709',
    projectId: 'flash-card-15cb1',
    authDomain: 'flash-card-15cb1.firebaseapp.com',
    storageBucket: 'flash-card-15cb1.appspot.com',
    measurementId: 'G-BT6F12J0YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-giH0SoVqukHq7JRmgjwbY82GD6dpfE',
    appId: '1:340037914709:android:880ebf12f47eba5c3ec4dc',
    messagingSenderId: '340037914709',
    projectId: 'flash-card-15cb1',
    storageBucket: 'flash-card-15cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6nu4JqPbXVvA2krke6BZMX_iMI9rhAko',
    appId: '1:340037914709:ios:fd7c36a7d14840883ec4dc',
    messagingSenderId: '340037914709',
    projectId: 'flash-card-15cb1',
    storageBucket: 'flash-card-15cb1.appspot.com',
    iosClientId: '340037914709-jp74ad88vfaeoeni6lbdscmuoa3jr19b.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6nu4JqPbXVvA2krke6BZMX_iMI9rhAko',
    appId: '1:340037914709:ios:fd7c36a7d14840883ec4dc',
    messagingSenderId: '340037914709',
    projectId: 'flash-card-15cb1',
    storageBucket: 'flash-card-15cb1.appspot.com',
    iosClientId: '340037914709-jp74ad88vfaeoeni6lbdscmuoa3jr19b.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
